### ISSUE TITLE
action_controller/caching/actions.rb normalize! breaks because it calls URI.parser.escape with a symbol

### ISSUE THREAD

**Issue by mobilutz** [rails/actionpack-action_caching#10]
I get this error:
NoMethodError (undefined method `gsub' for :json:Symbol):
  /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/uri/common.rb:304:in`escape'
  vendor/bundle/ruby/2.0.0/gems/actionpack-action_caching-1.1.0/lib/action_controller/caching/actions.rb:202:in `normalize!'
  vendor/bundle/ruby/2.0.0/gems/actionpack-action_caching-1.1.0/lib/action_controller/caching/actions.rb:197:in`initialize'
  vendor/bundle/ruby/2.0.0/gems/actionpack-action_caching-1.1.0/lib/action_controller/caching/actions.rb:165:in `new'

When I add a ".to_s" to the URI.parser.escape call in line 202 it works.

Could you maybe fix this? Thanks

**Comment by mattymess** [comment]
Is this ever going to make its way into rubygems so I don't have to point my gemfile to the repo?
