### ISSUE TITLE
Argument syntax problem?

### ISSUE THREAD

**Issue by lannn** [rails/actionpack-action_caching#15]
With syntax:
caches_action :feed, cache_path: Proc.new do
    if params[:user_id]
      user_list_url(params[:user_id], params[:id])
    else
      list_url(params[:id])
    end
  end

=> cache_path will receive Proc.new as the first required argument, and remain as a block
- Instead, syntax should like:
  caches_action :feed, cache_path: (Proc.new do
  if params[:user_id]
    user_list_url(params[:user_id], params[:id])
  else
    list_url(params[:id])
  end
  end)

**Comment by jclemans** [comment]
Using the example syntax of
```
caches_action :index, if: Proc.new do
    !request.format.json?  # cache if is not a JSON request
end
```
Causing me to get a `ArgumentError (tried to create Proc object without a block)` error.

**Comment by bitcoder** [comment]
the "if" also causes the same problem as @jclemans referrers. it seems that "if" does not work any way..

**Comment by nadavb** [comment]
Was the problem solved?

**Comment by pixeltrix** [comment]
Updated the README so that examples don't generate errors in 900e4add3aa531df1e6b01156e011ef7d642039f
