### ISSUE TITLE
Workaround required when you want to cache JSON output that isn't explicitly params[:format] = "json"

### ISSUE THREAD

**Issue by bramski** [rails/actionpack-action_caching#18]
If you are simply producing JSON responses from your action, say, as an API call, the action_cache implicitly makes your response of content-type: "html" despite what your render may actually be doing.  The workaround for this is to explicitly set the "format" to "json"

**Comment by keepcosmos** [comment]
As @cimm said, use default format. 
But on rail 4.1, `NoMethodError - undefined method 'gsub' for :json:Symbol` is occured
Use String.
```ruby
namespace :api, defaults: { format: 'json' } do
end
```
It works to me

**Comment by johnnagro** [comment]
@cimm @keepcosmos +1

**Comment by hernanvicente** [comment]
+1 keepcosmos

**Comment by hernanvicente** [comment]
+1 @keepcosmos

**Comment by sergiotapia** [comment]
For would be Binger's in Rails 5.

`get 'api/data', format: 'json'`

No more weird text/html for your cached json responses.
