### ISSUE TITLE
Assets precompile

### ISSUE THREAD

**Issue by tanguyantoine** [rails/actionpack-action_caching#27]
How do you manage deployments ?

caches_action cache all page and is not aware if assets are recompiled. 

Fingerprint is changing each time. I use `Rails.application.assets.digest` in cache path to ensure to  have rights assets name.

How do you do? 

Introducing `Rails.application.assets.digest` by default in cache path is reasonable?

**Comment by tanguyantoine** [comment]
No idea?

**Comment by hajder** [comment]
@tanguyantoine  Clean cache on deployment. You should ALWAYS do that.
