### ISSUE TITLE
Not Compatible with Rails 5

### ISSUE THREAD

**Issue by michaelholloway** [rails/actionpack-action_caching#36]
actionpack-action_caching was resolved to 1.0.0, which depends on
      actionpack (< 5.0, >= 4.0.0.beta)

Will this support Rails 5 soon?

**Comment by stevecj** [comment]
It looks like there is a PR that has been open for a long time at https://github.com/rails/actionpack-action_caching/pull/33/files .

**Comment by kiote** [comment]
ouch! Any news here?

**Comment by rafaelfranca** [comment]
Tracking things in #33

**Comment by jDeppen** [comment]
In case anyone else needs it, this is working for me (same with actionpack-page_caching):
`gem 'actionpack-action_caching', git: 'https://github.com/rails/actionpack-action_caching.git'`

**Comment by frankjdelgado** [comment]
I tried using the gem trick but that didn't work for me. Instead i added `include ActionController::Caching` to the application_controller.rb file. More info here: https://github.com/rails-api/rails-api/issues/25
