### ISSUE TITLE
Release date in 1.2.0 is wrong - should be 2017 not 2014

### ISSUE THREAD

**Issue by joelpresence** [rails/actionpack-action_caching#41]
In Changelog.md, the release date for version 1.2.0 is listed as January 23, 2014 but the year is wrong, it should be January 23, 2017.

Could we update this please?

I was very confused by the changelog when I saw this ancient date.  :-)

Thanks for releasing this update though, much appreciated!

**Comment by amatsuda** [comment]
@joelpresence Thank you!
