### ISSUE TITLE
caches_action with layout: false produces escaped html output on uncached response

### ISSUE THREAD

**Issue by jonn** [rails/actionpack-action_caching#43]
As of actionpack-action_caching 1.2.0, I’m getting escaped HTML for the output of a <code>caches_action</code> action when there is no cache to serve. When the action is already cached, the HTML output is not escaped and pages look/function as expected.

```
class HomeController < ApplicationController

  caches_action :index, layout: false

  …

end
```
Reverting to actionpack-action_caching 1.1.1 restores the expected behavior (html not escaped whether action output is cached or not).

**Comment by jonn** [comment]
Ha! Just saw this has been reported and fixed. Sorry for the noise.

**Comment by jonn** [comment]
Sorry, more noise. I miss-read the closed tickets. This is a new bug.

**Comment by nazarok** [comment]
this PR #42 fix it

**Comment by jonn** [comment]
Yes, I have confirmed that the change in PR #42 fixes this problem with actionpack-action_caching 1.2.0 for me. Thanks @nazarok!

**Comment by jogaco** [comment]
Bitten by this. Any chance for this being merged?

**Comment by adambutler** [comment]
I've too had this issue... but secondly, I am getting my layout inside my layout...

![screen shot 2017-07-19 at 11 40 21](https://user-images.githubusercontent.com/1238468/28363149-471803e4-6c77-11e7-9662-32529af06c3c.png)

My guess was that the originally the page + layout was cached so ran `rake tmp:cache:clear` but this has not resolved the issue.

I believe this was also raised (but misunderstood) by @vishaljagtap-tudip at [this comment](https://github.com/rails/actionpack-action_caching/issues/47#issuecomment-303156966).

@jonn @jogaco @nazarok @antulik Have you experienced this issue?

**Comment by jogaco** [comment]
Don't remember if I had layout inside layout. I do remember escaped html output. I am now using @antulik fork which solves the problem

**Comment by adambutler** [comment]
@jogaco Thanks, tried using the fork, no luck.

**Comment by jogaco** [comment]
Just checked.
This works for me:
`gem 'actionpack-action_caching', github: 'antulik/actionpack-action_caching', ref: '8c6e52c69315d67437f480da5dce4b7c8737fb32'`

This produces an escaped html output.
`gem 'actionpack-action_caching'`

**Comment by panaak** [comment]
also checked and @antulik fork fixes the problem for me.

**Comment by jskulski** [comment]
Ran into this and #42 works for us.

**Comment by snowblink** [comment]
@rafaelfranca any chance of getting this merged and a new release out please?
