### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by frammnm** [rails/actionpack-action_caching#45]
Hello,  i want to do some caching on a rails backend that i got and i want to benchmark the results, i have been measuring with Postman the query time results and i have been doing mostly action caching. 
I wanna compare the disk store and the mem store, the first weird thing that i notice is that when using the disk store the files are not being created, i am not sure why even tho i specified the path in the configuration file, also i am doing this bench-marking in a development environment. I was wondering if there was a smarter way to do it, or to verify the correct functionality of the gem.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
