### ISSUE TITLE
Ability to invalidate cache on an action call or event

### ISSUE THREAD

**Issue by yaxhpal** [rails/actionpack-action_caching#51]
The actionpack-action_caching provides mechanism to invalidate cached actions by providing `:expires_in` with a time interval. For example:
```
# expire cache after an hour
caches_action :archived, expires_in: 1.hour
```
But, I couldn't find way to invalidate cache if particular action is called or a specific page is requested. Why I need this? I am caching `index action` of a products page but I want cache to be expired if someone creates new products which is a very rare but a real situation. 

Do we already have this functionality or May be I am not able to figure it out. Could you please help?

**Comment by traviskroberts** [comment]
@yaxhpal You should be able to accomplish that with [observers/sweepers](https://github.com/rails/rails-observers#action-controller-sweeper).

**Comment by yaxhpal** [comment]
@traviskroberts Thanks for the suggestion. I will definitely try this and post here what I have done.

**Comment by yaxhpal** [comment]
Finally, got it working like this: 

```
expire_action action: "index", controller: "products"
```

Thank you for pointing me to right direction.

**Comment by zedtux** [comment]
I need to do the same as @yaxhpal, and I have implemented a Sweeper in my application, but when it runs, it fails with:

```bash
NoMethodError: undefined method `expire_action' for #<FormulasSweeper:0x00000004fc8ee8 @_routes=nil, @controller=nil>
/bundle/gems/rails-observers-0.1.5/lib/rails/observers/action_controller/caching/sweeper.rb:56:in `method_missing'
app/sweepers/formulas_sweeper.rb:7:in `after_update'
...
```

**Comment by traviskroberts** [comment]
@zedtux Hmm, the only thing I can think of (looking at the [source of the error](https://github.com/rails/rails-observers/blob/v0.1.5/lib/rails/observers/action_controller/caching/sweeper.rb#L56)), is that you might have the controller name wrong in your call to `expire_action`. Can you double check that it's correct?

**Comment by zedtux** [comment]
Thank you @traviskroberts for your comment.

My controller is named `FormulasController` so it should be fine or am I wrong?
