### ISSUE TITLE
NoMethodError: undefined method `expire_action' for #<FormulasSweeper:0x00000004e935f0 @controller=nil>

### ISSUE THREAD

**Issue by zedtux** [rails/actionpack-action_caching#54]
I have the same issue but in my running application (not RSpec) with rails 5.1.4.

In my controller:

```ruby
class FormulasController < ApplicationController
  ...
  caches_action :index
  cache_sweeper :formulas_sweeper, only: :index

  def index
    ...
  end
end
```

And my Sweeper class:

```ruby
class FormulasSweeper < ActionController::Caching::Sweeper
  observe Import

  def after_update(import)
    expire_action controller: 'formulas', action: 'index'
  end
end
```

The Sweeper is running and failing with the following error when I'm updating an `Import` from the Rails console, or from a Sidekiq job:

```bash
NoMethodError: undefined method `expire_action' for #<FormulasSweeper:0x00000004e935f0 @controller=nil>
	from app/sweepers/formulas_sweeper.rb:6:in `after_update'
	from (irb):2
```

## @nnattawat's fix from rails/rails-observers#31

Updating my Sweeper as following:

```ruby
class FormulasSweeper < ActionController::Caching::Sweeper
  observe Import

  def after_update(import)
    @controller ||= ActionController::Base.new
    expire_action controller: 'formulas', action: 'index'
  end
end
```

Makes the code fail with:

```bash
NoMethodError: undefined method `host' for nil:NilClass
	from app/sweepers/formulas_sweeper.rb:7:in `after_update'
	from (irb):2
```

This is due to the fact that [`ActionController::UrlFor.url_options`](https://github.com/rails/rails/blob/v5.1.4/actionpack/lib/action_controller/metal/url_for.rb#L30) is expecting a `request` object which is `nil` in my case.

**Comment by zedtux** [comment]
I finally found a way to make it working ... not perfect but working.

In my controller I set the `:cache_path`:

```ruby
class FormulasController < ApplicationController
  ...
  caches_action :index, cache_path: 'formulas'
  cache_sweeper :formulas_sweeper, only: :index

  def index
    ...
  end
end
```

And then I expire the fragment myself in my Sweeper:

```ruby
class FormulasSweeper < ActionController::Caching::Sweeper
  observe Import

  def after_update(import)
    ActionController::Base.new.expire_fragment('formulas')
  end
end
```

**Comment by zedtux** [comment]
Thank you @dgmstuart for your contributions and @angelmmiguel for merging the PR. Does this mean this issue can be closed ?

**Comment by Angelmmiguel** [comment]
@zedtux yes, I think you can close it. The only difference with the code above is to use ` self.controller=`  instead of `@controller`:

```
self.controller ||= ActionController::Base.new
```

Btw, the PR was merged but the new version is not released yet.
