### ISSUE TITLE
rails-6 support

### ISSUE THREAD

**Issue by ojab** [rails/actionpack-action_caching#67]
I see that master can work with rails-6 just fine, can I have a release with that changes?

**Comment by jonatasdaniel** [comment]
@ojab which version are you using? I'm trying `1.2.0` with rails `6.0.0` and it's not working. It seems the gem needs action pack < 6, and I'm using `6.0.0`.

**Comment by ojab** [comment]
There is no released version yet, so directly from github:
`gem 'actionpack-action_caching', github: 'rails/actionpack-action_caching'`

**Comment by rafaelfranca** [comment]
1.2.1 Released with those changes
